// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module MSHR_10(
  input         clock,
                reset,
                io_req_pri_val,
                io_req_sec_val,
  input  [39:0] io_req_bits_addr,
  input  [6:0]  io_req_bits_tag,
  input  [4:0]  io_req_bits_cmd,
  input  [1:0]  io_req_bits_size,
  input         io_req_bits_signed,
  input  [1:0]  io_req_bits_dprv,
  input         io_req_bits_dv,
                io_req_bits_phys,
                io_req_bits_no_alloc,
                io_req_bits_no_xcpt,
  input  [4:0]  io_req_bits_sdq_id,
  input         io_req_bits_tag_match,
  input  [1:0]  io_req_bits_old_meta_coh_state,
  input  [21:0] io_req_bits_old_meta_tag,
  input  [3:0]  io_req_bits_way_en,
  input         io_mem_acquire_ready,
                io_mem_grant_valid,
  input  [2:0]  io_mem_grant_bits_opcode,
  input  [1:0]  io_mem_grant_bits_param,
  input  [3:0]  io_mem_grant_bits_size,
  input  [2:0]  io_mem_grant_bits_sink,
  input         io_mem_finish_ready,
                io_meta_read_ready,
                io_meta_write_ready,
                io_replay_ready,
                io_wb_req_ready,
  output        io_req_pri_rdy,
                io_req_sec_rdy,
                io_idx_match,
  output [21:0] io_tag,
  output        io_mem_acquire_valid,
  output [2:0]  io_mem_acquire_bits_param,
  output [31:0] io_mem_acquire_bits_address,
  output        io_mem_finish_valid,
  output [2:0]  io_mem_finish_bits_sink,
  output [3:0]  io_refill_way_en,
  output [9:0]  io_refill_addr,
  output        io_meta_read_valid,
  output [3:0]  io_meta_read_bits_idx,
  output        io_meta_write_valid,
  output [3:0]  io_meta_write_bits_idx,
                io_meta_write_bits_way_en,
  output [1:0]  io_meta_write_bits_data_coh_state,
  output [21:0] io_meta_write_bits_data_tag,
  output        io_replay_valid,
  output [39:0] io_replay_bits_addr,
  output [6:0]  io_replay_bits_tag,
  output [4:0]  io_replay_bits_cmd,
  output [1:0]  io_replay_bits_size,
  output        io_replay_bits_signed,
  output [1:0]  io_replay_bits_dprv,
  output [4:0]  io_replay_bits_sdq_id,
  output        io_wb_req_valid,
  output [21:0] io_wb_req_bits_tag,
  output [3:0]  io_wb_req_bits_idx,
  output [2:0]  io_wb_req_bits_param,
  output [3:0]  io_wb_req_bits_way_en,
  output        io_probe_rdy
);

  wire             _io_req_pri_rdy_output;	// @[NBDcache.scala:197:75]
  wire             _grantackq_io_enq_ready;	// @[NBDcache.scala:257:25]
  wire             _grantackq_io_deq_valid;	// @[NBDcache.scala:257:25]
  wire             _rpq_io_enq_ready;	// @[NBDcache.scala:194:19]
  wire             _rpq_io_deq_valid;	// @[NBDcache.scala:194:19]
  wire [39:0]      _rpq_io_deq_bits_addr;	// @[NBDcache.scala:194:19]
  wire [4:0]       _rpq_io_deq_bits_cmd;	// @[NBDcache.scala:194:19]
  reg  [3:0]       state;	// @[NBDcache.scala:168:22]
  reg  [39:0]      req_addr;	// @[NBDcache.scala:170:16]
  reg  [4:0]       req_cmd;	// @[NBDcache.scala:170:16]
  reg  [1:0]       req_old_meta_coh_state;	// @[NBDcache.scala:170:16]
  reg  [21:0]      req_old_meta_tag;	// @[NBDcache.scala:170:16]
  reg  [3:0]       req_way_en;	// @[NBDcache.scala:170:16]
  wire             idx_match = req_addr[9:6] == io_req_bits_addr[9:6];	// @[NBDcache.scala:170:16, :171:25, :174:{27,47}]
  reg  [1:0]       new_coh_state;	// @[NBDcache.scala:176:24]
  wire             _needs_second_acq_T_27 = req_cmd == 5'h1;	// @[Consts.scala:86:32, NBDcache.scala:170:16]
  wire             _needs_second_acq_T_28 = req_cmd == 5'h11;	// @[Consts.scala:86:49, NBDcache.scala:170:16]
  wire             _needs_second_acq_T_30 = req_cmd == 5'h7;	// @[Consts.scala:86:66, NBDcache.scala:170:16]
  wire             _needs_second_acq_T_32 = req_cmd == 5'h4;	// @[NBDcache.scala:170:16, package.scala:16:47]
  wire             _needs_second_acq_T_33 = req_cmd == 5'h9;	// @[NBDcache.scala:170:16, package.scala:16:47]
  wire             _needs_second_acq_T_34 = req_cmd == 5'hA;	// @[NBDcache.scala:170:16, package.scala:16:47]
  wire             _needs_second_acq_T_35 = req_cmd == 5'hB;	// @[NBDcache.scala:170:16, package.scala:16:47]
  wire             _needs_second_acq_T_39 = req_cmd == 5'h8;	// @[NBDcache.scala:170:16, package.scala:16:47]
  wire             _needs_second_acq_T_40 = req_cmd == 5'hC;	// @[NBDcache.scala:170:16, package.scala:16:47]
  wire             _needs_second_acq_T_41 = req_cmd == 5'hD;	// @[NBDcache.scala:170:16, package.scala:16:47]
  wire             _needs_second_acq_T_42 = req_cmd == 5'hE;	// @[NBDcache.scala:170:16, package.scala:16:47]
  wire             _needs_second_acq_T_43 = req_cmd == 5'hF;	// @[NBDcache.scala:170:16, package.scala:16:47]
  wire             _needs_second_acq_T_50 = req_cmd == 5'h3;	// @[Consts.scala:87:54, NBDcache.scala:170:16]
  wire             _needs_second_acq_T_52 = req_cmd == 5'h6;	// @[Consts.scala:87:71, NBDcache.scala:170:16]
  wire [3:0]       _grow_param_T = {_needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43, _needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43 | _needs_second_acq_T_50 | _needs_second_acq_T_52, new_coh_state};	// @[Cat.scala:33:92, Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, NBDcache.scala:176:24, package.scala:16:47]
  wire [1:0]       _grow_param_T_27 = {1'h0, _grow_param_T == 4'hC};	// @[Cat.scala:33:92, Misc.scala:34:36, :48:20, NBDcache.scala:170:16, package.scala:16:47]
  wire [15:0][1:0] _GEN = {{2'h3}, {2'h3}, {2'h2}, {_grow_param_T_27}, {_grow_param_T_27}, {_grow_param_T_27}, {_grow_param_T_27}, {_grow_param_T_27}, {2'h3}, {2'h2}, {2'h2}, {2'h1}, {2'h3}, {2'h2}, {2'h1}, {2'h0}};	// @[Cat.scala:33:92, Metadata.scala:161:16, Misc.scala:34:36, :48:20, Mux.scala:81:58]
  wire             _c_cat_T_123 = io_req_bits_cmd == 5'h1;	// @[Consts.scala:86:32]
  wire             _c_cat_T_124 = io_req_bits_cmd == 5'h11;	// @[Consts.scala:86:49]
  wire             _c_cat_T_126 = io_req_bits_cmd == 5'h7;	// @[Consts.scala:86:66]
  wire             _c_cat_T_128 = io_req_bits_cmd == 5'h4;	// @[package.scala:16:47]
  wire             _c_cat_T_129 = io_req_bits_cmd == 5'h9;	// @[package.scala:16:47]
  wire             _c_cat_T_130 = io_req_bits_cmd == 5'hA;	// @[package.scala:16:47]
  wire             _c_cat_T_131 = io_req_bits_cmd == 5'hB;	// @[package.scala:16:47]
  wire             _c_cat_T_135 = io_req_bits_cmd == 5'h8;	// @[package.scala:16:47]
  wire             _c_cat_T_136 = io_req_bits_cmd == 5'hC;	// @[package.scala:16:47]
  wire             _c_cat_T_137 = io_req_bits_cmd == 5'hD;	// @[package.scala:16:47]
  wire             _c_cat_T_138 = io_req_bits_cmd == 5'hE;	// @[package.scala:16:47]
  wire             _c_cat_T_139 = io_req_bits_cmd == 5'hF;	// @[package.scala:16:47]
  wire             _c_cat_T_146 = io_req_bits_cmd == 5'h3;	// @[Consts.scala:87:54]
  wire             _c_cat_T_148 = io_req_bits_cmd == 5'h6;	// @[Consts.scala:87:71]
  wire [26:0]      _beats1_decode_T_1 = 27'hFFF << io_mem_grant_bits_size;	// @[package.scala:235:71]
  wire [8:0]       beats1 = io_mem_grant_bits_opcode[0] ? ~(_beats1_decode_T_1[11:3]) : 9'h0;	// @[Edges.scala:106:36, :221:14, :229:27, package.scala:235:{46,71,76}]
  reg  [8:0]       counter;	// @[Edges.scala:229:27]
  wire [8:0]       counter1 = counter - 9'h1;	// @[Edges.scala:229:27, :230:28]
  wire             refill_done = (counter == 9'h1 | beats1 == 9'h0) & io_mem_grant_valid;	// @[Edges.scala:221:14, :229:27, :232:{25,33,43}, :233:22]
  wire [6:0]       _GEN_0 = beats1[6:0] & ~(counter1[6:0]);	// @[Edges.scala:221:14, :230:28, :234:{25,27}]
  wire             _io_wb_req_valid_output = state == 4'h1;	// @[NBDcache.scala:168:22, package.scala:16:47]
  wire             _io_probe_rdy_T_2 = state == 4'h2;	// @[NBDcache.scala:168:22, package.scala:16:47]
  wire             _io_meta_write_bits_data_coh_T = state == 4'h3;	// @[NBDcache.scala:168:22, package.scala:16:47]
  wire             _io_mem_acquire_valid_T = state == 4'h4;	// @[NBDcache.scala:168:22, package.scala:16:47]
  wire             _T_194 = state == 4'h5;	// @[NBDcache.scala:168:22, package.scala:16:47]
  wire             sec_rdy = idx_match & (_io_wb_req_valid_output | _io_probe_rdy_T_2 | _io_meta_write_bits_data_coh_T | (_io_mem_acquire_valid_T | _T_194) & ~((_c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139 | _c_cat_T_146 | _c_cat_T_148) & ~(_needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43 | _needs_second_acq_T_50 | _needs_second_acq_T_52)) & ~refill_done);	// @[Consts.scala:86:{32,49,66}, :87:{54,64,71}, Edges.scala:233:22, Metadata.scala:104:{54,57}, NBDcache.scala:174:27, :189:27, :190:56, :192:{23,52,55}, package.scala:16:47, :73:59]
  wire             _T_204 = io_req_pri_val & _io_req_pri_rdy_output;	// @[NBDcache.scala:195:39, :197:75]
  wire             _io_replay_valid_T = state == 4'h8;	// @[NBDcache.scala:168:22, :197:49, package.scala:16:47]
  assign _io_req_pri_rdy_output = state == 4'h0;	// @[NBDcache.scala:168:22, :197:75]
  reg              acked;	// @[NBDcache.scala:199:18]
  wire             _io_meta_write_valid_T = state == 4'h6;	// @[NBDcache.scala:168:22, :209:15]
  wire             can_finish = _io_req_pri_rdy_output | _io_mem_acquire_valid_T;	// @[NBDcache.scala:197:75, package.scala:16:47, :73:59]
  wire             _io_req_sec_rdy_output = sec_rdy & _rpq_io_enq_ready;	// @[NBDcache.scala:189:27, :194:19, :270:29]
  reg  [1:0]       meta_hazard;	// @[NBDcache.scala:272:28]
  wire             _io_meta_write_valid_output = _io_meta_write_valid_T | _io_meta_write_bits_data_coh_T;	// @[NBDcache.scala:209:15, package.scala:16:47, :73:59]
  wire             _io_mem_acquire_valid_output = _io_mem_acquire_valid_T & _grantackq_io_enq_ready;	// @[NBDcache.scala:257:25, :292:50, package.scala:16:47]
  wire [3:0]       _T_205 = {_c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139, _c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139 | _c_cat_T_146 | _c_cat_T_148, io_req_bits_old_meta_coh_state};	// @[Cat.scala:33:92, Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, package.scala:16:47]
  wire             is_hit = _T_205 == 4'h3 | _T_205 == 4'h2 | _T_205 == 4'h1 | _T_205 == 4'h7 | _T_205 == 4'h6 | (&_T_205) | _T_205 == 4'hE;	// @[Cat.scala:33:92, Misc.scala:34:9, :48:20, NBDcache.scala:205:15, :209:15, package.scala:16:47]
  wire [1:0]       _T_232 = {1'h0, _T_205 == 4'hC};	// @[Cat.scala:33:92, Misc.scala:34:36, :48:20, NBDcache.scala:170:16, package.scala:16:47]
  wire [15:0][1:0] _GEN_1 = {{2'h3}, {2'h3}, {2'h2}, {_T_232}, {_T_232}, {_T_232}, {_T_232}, {_T_232}, {2'h3}, {2'h2}, {2'h2}, {2'h1}, {2'h3}, {2'h2}, {2'h1}, {2'h0}};	// @[Cat.scala:33:92, Metadata.scala:161:16, Misc.scala:34:36, :48:20, Mux.scala:81:58]
  wire [3:0]       _coh_on_grant_T = {_needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43, _needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43 | _needs_second_acq_T_50 | _needs_second_acq_T_52, io_mem_grant_bits_param};	// @[Cat.scala:33:92, Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, package.scala:16:47]
  wire [3:0]       _T_66 = {_needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43, _needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43 | _needs_second_acq_T_50 | _needs_second_acq_T_52, new_coh_state};	// @[Cat.scala:33:92, Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, NBDcache.scala:176:24, package.scala:16:47]
  wire [3:0]       _T_127 = {_c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139, _c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139 | _c_cat_T_146 | _c_cat_T_148, new_coh_state};	// @[Cat.scala:33:92, Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, NBDcache.scala:176:24, package.scala:16:47]
  wire             _T_195 = _T_194 & refill_done;	// @[Edges.scala:233:22, NBDcache.scala:212:33, package.scala:16:47]
  wire [1:0]       _T_154 = {1'h0, _T_127 == 4'hC};	// @[Cat.scala:33:92, Misc.scala:34:36, :48:20, NBDcache.scala:170:16, package.scala:16:47]
  wire [15:0][1:0] _GEN_2 = {{2'h3}, {2'h3}, {2'h2}, {_T_154}, {_T_154}, {_T_154}, {_T_154}, {_T_154}, {2'h3}, {2'h2}, {2'h2}, {2'h1}, {2'h3}, {2'h2}, {2'h1}, {2'h0}};	// @[Cat.scala:33:92, Metadata.scala:161:16, Misc.scala:34:36, :48:20, Mux.scala:81:58]
  wire [1:0]       _T_93 = {1'h0, _T_66 == 4'hC};	// @[Cat.scala:33:92, Misc.scala:34:36, :48:20, NBDcache.scala:170:16, package.scala:16:47]
  wire [15:0][1:0] _GEN_3 = {{2'h3}, {2'h3}, {2'h2}, {_T_93}, {_T_93}, {_T_93}, {_T_93}, {_T_93}, {2'h3}, {2'h2}, {2'h2}, {2'h1}, {2'h3}, {2'h2}, {2'h1}, {2'h0}};	// @[Cat.scala:33:92, Metadata.scala:161:16, Misc.scala:34:36, :48:20, Mux.scala:81:58]
  wire [1:0]       dirties_cat = {_c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139, _c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139 | _c_cat_T_146 | _c_cat_T_148};	// @[Cat.scala:33:92, Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, package.scala:16:47]
  wire             _T_203 = io_req_sec_val & _io_req_sec_rdy_output;	// @[NBDcache.scala:228:24, :270:29]
  always @(posedge clock) begin
    if (reset) begin
      state <= 4'h0;	// @[NBDcache.scala:168:22]
      new_coh_state <= 2'h0;	// @[Metadata.scala:161:16, NBDcache.scala:176:24]
      counter <= 9'h0;	// @[Edges.scala:229:27]
      meta_hazard <= 2'h0;	// @[Metadata.scala:161:16, NBDcache.scala:272:28]
    end
    else begin
      if (_T_204) begin	// @[NBDcache.scala:195:39]
        if (io_req_bits_tag_match) begin
          state <= {2'h1, is_hit, 1'h0};	// @[Misc.scala:34:9, Mux.scala:81:58, NBDcache.scala:168:22, :170:16, :244:21, :246:15, :249:15]
          if (is_hit)	// @[Misc.scala:34:9]
            new_coh_state <= _GEN_1[_T_205];	// @[Cat.scala:33:92, Misc.scala:34:36, :48:20, NBDcache.scala:176:24]
          else	// @[Misc.scala:34:9]
            new_coh_state <= io_req_bits_old_meta_coh_state;	// @[NBDcache.scala:176:24]
        end
        else begin
          state <= {2'h0, io_req_bits_old_meta_coh_state != 2'h3, 1'h1};	// @[Cat.scala:33:92, Metadata.scala:161:16, Misc.scala:37:9, :55:20, NBDcache.scala:168:22, :253:19]
          new_coh_state <= 2'h0;	// @[Metadata.scala:161:16, NBDcache.scala:176:24]
        end
      end
      else begin	// @[NBDcache.scala:195:39]
        if (io_wb_req_ready & _io_wb_req_valid_output)	// @[Decoupled.scala:51:35, package.scala:16:47]
          state <= 4'h2;	// @[NBDcache.scala:168:22, package.scala:16:47]
        else if (_io_probe_rdy_T_2 & io_wb_req_ready & acked)	// @[NBDcache.scala:199:18, :222:48, package.scala:16:47]
          state <= 4'h3;	// @[NBDcache.scala:168:22, package.scala:16:47]
        else if (_io_meta_write_bits_data_coh_T & io_meta_write_ready)	// @[NBDcache.scala:219:32, package.scala:16:47]
          state <= 4'h4;	// @[NBDcache.scala:168:22, package.scala:16:47]
        else if (io_mem_acquire_ready & _io_mem_acquire_valid_output)	// @[Decoupled.scala:51:35, NBDcache.scala:292:50]
          state <= 4'h5;	// @[NBDcache.scala:168:22, package.scala:16:47]
        else if (_T_195)	// @[NBDcache.scala:212:33]
          state <= 4'h6;	// @[NBDcache.scala:168:22, :209:15]
        else if (_io_meta_write_valid_T & io_meta_write_ready)	// @[NBDcache.scala:209:{15,36}]
          state <= 4'h7;	// @[NBDcache.scala:168:22, :205:15]
        else if (state == 4'h7)	// @[NBDcache.scala:168:22, :205:15]
          state <= 4'h8;	// @[NBDcache.scala:168:22, package.scala:16:47]
        else if (_io_replay_valid_T & ~_rpq_io_deq_valid)	// @[NBDcache.scala:194:19, :197:49, :202:{31,34}]
          state <= 4'h0;	// @[NBDcache.scala:168:22]
        if (_T_203 & (_T_66 == 4'h3 | _T_66 == 4'h2 | _T_66 == 4'h1 | _T_66 == 4'h7 | _T_66 == 4'h6 | (&_T_66) | _T_66 == 4'hE) & (_T_127 == 4'h3 | _T_127 == 4'h2 | _T_127 == 4'h1 | _T_127 == 4'h7 | _T_127 == 4'h6 | (&_T_127) | _T_127 == 4'hE)) begin	// @[Cat.scala:33:92, Misc.scala:34:9, :48:20, NBDcache.scala:205:15, :209:15, :212:49, :228:{24,43}, :233:25, :234:15, package.scala:16:47]
          if (&dirties_cat)	// @[Cat.scala:33:92, Metadata.scala:106:42]
            new_coh_state <= _GEN_2[_T_127];	// @[Cat.scala:33:92, Misc.scala:34:36, :48:20, NBDcache.scala:176:24]
          else	// @[Metadata.scala:106:42]
            new_coh_state <= _GEN_3[_T_66];	// @[Cat.scala:33:92, Misc.scala:34:36, :48:20, NBDcache.scala:176:24]
        end
        else if (_T_195) begin	// @[NBDcache.scala:212:33]
          if (_coh_on_grant_T == 4'hC)	// @[Cat.scala:33:92, Mux.scala:81:61, package.scala:16:47]
            new_coh_state <= 2'h3;	// @[Cat.scala:33:92, NBDcache.scala:176:24]
          else if (_coh_on_grant_T == 4'h4 | _coh_on_grant_T == 4'h0)	// @[Cat.scala:33:92, Mux.scala:81:{58,61}, NBDcache.scala:168:22, package.scala:16:47]
            new_coh_state <= 2'h2;	// @[Mux.scala:81:58, NBDcache.scala:176:24]
          else	// @[Mux.scala:81:58]
            new_coh_state <= {1'h0, _coh_on_grant_T == 4'h1};	// @[Cat.scala:33:92, Mux.scala:81:{58,61}, NBDcache.scala:170:16, :176:24, package.scala:16:47]
        end
      end
      if (io_mem_grant_valid) begin
        if (counter == 9'h0) begin	// @[Edges.scala:229:27, :231:25]
          if (io_mem_grant_bits_opcode[0])	// @[Edges.scala:106:36]
            counter <= ~(_beats1_decode_T_1[11:3]);	// @[Edges.scala:229:27, package.scala:235:{46,71,76}]
          else	// @[Edges.scala:106:36]
            counter <= 9'h0;	// @[Edges.scala:229:27]
        end
        else	// @[Edges.scala:231:25]
          counter <= counter1;	// @[Edges.scala:229:27, :230:28]
      end
      if (io_meta_write_ready & _io_meta_write_valid_output)	// @[Decoupled.scala:51:35, package.scala:73:59]
        meta_hazard <= 2'h1;	// @[Mux.scala:81:58, NBDcache.scala:272:28]
      else if (|meta_hazard)	// @[NBDcache.scala:272:28, :273:21]
        meta_hazard <= meta_hazard + 2'h1;	// @[Mux.scala:81:58, NBDcache.scala:272:28, :273:59]
    end
    if (_T_204) begin	// @[NBDcache.scala:195:39]
      req_addr <= io_req_bits_addr;	// @[NBDcache.scala:170:16]
      req_old_meta_coh_state <= io_req_bits_old_meta_coh_state;	// @[NBDcache.scala:170:16]
      req_old_meta_tag <= io_req_bits_old_meta_tag;	// @[NBDcache.scala:170:16]
      req_way_en <= io_req_bits_way_en;	// @[NBDcache.scala:170:16]
    end
    if (_T_204 | _T_203 & (&dirties_cat))	// @[Cat.scala:33:92, Metadata.scala:106:42, :109:27, NBDcache.scala:170:16, :195:39, :228:{24,43}, :232:13, :237:43, :238:9]
      req_cmd <= io_req_bits_cmd;	// @[NBDcache.scala:170:16]
    acked <= ~_T_204 & (io_mem_grant_valid | acked);	// @[NBDcache.scala:195:39, :199:18, :200:{29,37}, :237:43, :239:11]
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        state = _RANDOM_0[3:0];	// @[NBDcache.scala:168:22]
        req_addr = {_RANDOM_0[31:4], _RANDOM_1[11:0]};	// @[NBDcache.scala:168:22, :170:16]
        req_cmd = _RANDOM_1[23:19];	// @[NBDcache.scala:170:16]
        req_old_meta_coh_state = _RANDOM_2[8:7];	// @[NBDcache.scala:170:16]
        req_old_meta_tag = _RANDOM_2[30:9];	// @[NBDcache.scala:170:16]
        req_way_en = {_RANDOM_2[31], _RANDOM_3[2:0]};	// @[NBDcache.scala:170:16]
        new_coh_state = _RANDOM_3[4:3];	// @[NBDcache.scala:170:16, :176:24]
        counter = _RANDOM_3[13:5];	// @[Edges.scala:229:27, NBDcache.scala:170:16]
        acked = _RANDOM_3[14];	// @[NBDcache.scala:170:16, :199:18]
        meta_hazard = _RANDOM_3[16:15];	// @[NBDcache.scala:170:16, :272:28]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  Queue_82 rpq (	// @[NBDcache.scala:194:19]
    .clock                (clock),
    .reset                (reset),
    .io_enq_valid         ((_T_204 | io_req_sec_val & sec_rdy) & ~(io_req_bits_cmd == 5'h2 | _c_cat_T_146)),	// @[Consts.scala:84:{35,45}, :87:54, NBDcache.scala:189:27, :195:{39,57,75,87,90}]
    .io_enq_bits_addr     (io_req_bits_addr),
    .io_enq_bits_tag      (io_req_bits_tag),
    .io_enq_bits_cmd      (io_req_bits_cmd),
    .io_enq_bits_size     (io_req_bits_size),
    .io_enq_bits_signed   (io_req_bits_signed),
    .io_enq_bits_dprv     (io_req_bits_dprv),
    .io_enq_bits_dv       (io_req_bits_dv),
    .io_enq_bits_phys     (io_req_bits_phys),
    .io_enq_bits_no_alloc (io_req_bits_no_alloc),
    .io_enq_bits_no_xcpt  (io_req_bits_no_xcpt),
    .io_enq_bits_sdq_id   (io_req_bits_sdq_id),
    .io_deq_ready         (io_meta_read_ready & (io_replay_ready & _io_replay_valid_T | _io_req_pri_rdy_output)),	// @[NBDcache.scala:197:{20,40,49,66,75}, :309:30, :310:22]
    .io_enq_ready         (_rpq_io_enq_ready),
    .io_deq_valid         (_rpq_io_deq_valid),
    .io_deq_bits_addr     (_rpq_io_deq_bits_addr),
    .io_deq_bits_tag      (io_replay_bits_tag),
    .io_deq_bits_cmd      (_rpq_io_deq_bits_cmd),
    .io_deq_bits_size     (io_replay_bits_size),
    .io_deq_bits_signed   (io_replay_bits_signed),
    .io_deq_bits_dprv     (io_replay_bits_dprv),
    .io_deq_bits_sdq_id   (io_replay_bits_sdq_id)
  );
  Queue_83 grantackq (	// @[NBDcache.scala:257:25]
    .clock            (clock),
    .reset            (reset),
    .io_enq_valid     (refill_done & io_mem_grant_bits_opcode[2] & ~(io_mem_grant_bits_opcode[1])),	// @[Edges.scala:71:{36,43,52}, :233:22, NBDcache.scala:259:41]
    .io_enq_bits_sink (io_mem_grant_bits_sink),
    .io_deq_ready     (io_mem_finish_ready & can_finish),	// @[NBDcache.scala:263:49, package.scala:73:59]
    .io_enq_ready     (_grantackq_io_enq_ready),
    .io_deq_valid     (_grantackq_io_deq_valid),
    .io_deq_bits_sink (io_mem_finish_bits_sink)
  );
  assign io_req_pri_rdy = _io_req_pri_rdy_output;	// @[NBDcache.scala:197:75]
  assign io_req_sec_rdy = _io_req_sec_rdy_output;	// @[NBDcache.scala:270:29]
  assign io_idx_match = (|state) & idx_match;	// @[NBDcache.scala:168:22, :174:27, :265:{26,41}]
  assign io_tag = req_addr[31:10];	// @[NBDcache.scala:170:16, :172:26, :268:10]
  assign io_mem_acquire_valid = _io_mem_acquire_valid_output;	// @[NBDcache.scala:292:50]
  assign io_mem_acquire_bits_param = {1'h0, _GEN[_grow_param_T]};	// @[Cat.scala:33:92, Edges.scala:349:15, Misc.scala:34:36, :48:20, NBDcache.scala:170:16]
  assign io_mem_acquire_bits_address = {req_addr[31:6], 6'h0};	// @[Cat.scala:33:92, NBDcache.scala:170:16, :173:51, :295:66]
  assign io_mem_finish_valid = _grantackq_io_deq_valid & can_finish;	// @[NBDcache.scala:257:25, :261:49, package.scala:73:59]
  assign io_refill_way_en = req_way_en;	// @[NBDcache.scala:170:16]
  assign io_refill_addr = {req_addr[9:6] | _GEN_0[6:3], _GEN_0[2:0], 3'h0};	// @[Edges.scala:234:25, Misc.scala:37:36, NBDcache.scala:170:16, :267:{18,36}]
  assign io_meta_read_valid = _io_replay_valid_T;	// @[NBDcache.scala:197:49]
  assign io_meta_read_bits_idx = req_addr[9:6];	// @[NBDcache.scala:170:16, :171:25]
  assign io_meta_write_valid = _io_meta_write_valid_output;	// @[package.scala:73:59]
  assign io_meta_write_bits_idx = req_addr[9:6];	// @[NBDcache.scala:170:16, :171:25]
  assign io_meta_write_bits_way_en = req_way_en;	// @[NBDcache.scala:170:16]
  assign io_meta_write_bits_data_coh_state = _io_meta_write_bits_data_coh_T ? 2'h0 : new_coh_state;	// @[Metadata.scala:161:16, NBDcache.scala:176:24, :280:37, package.scala:16:47]
  assign io_meta_write_bits_data_tag = req_addr[31:10];	// @[NBDcache.scala:170:16, :172:26, :268:10]
  assign io_replay_valid = _io_replay_valid_T & _rpq_io_deq_valid;	// @[NBDcache.scala:194:19, :197:49, :304:44]
  assign io_replay_bits_addr = {8'h0, req_addr[31:6], _rpq_io_deq_bits_addr[5:0]};	// @[Cat.scala:33:92, Edges.scala:232:25, NBDcache.scala:170:16, :194:19, :307:{23,67}]
  assign io_replay_bits_cmd = io_meta_read_ready ? _rpq_io_deq_bits_cmd : 5'h5;	// @[NBDcache.scala:194:19, :305:18, :309:30, :311:24]
  assign io_wb_req_valid = _io_wb_req_valid_output;	// @[package.scala:16:47]
  assign io_wb_req_bits_tag = req_old_meta_tag;	// @[NBDcache.scala:170:16]
  assign io_wb_req_bits_idx = req_addr[9:6];	// @[NBDcache.scala:170:16, :171:25]
  assign io_wb_req_bits_param = (&req_old_meta_coh_state) | req_old_meta_coh_state == 2'h2 ? 3'h1 : req_old_meta_coh_state == 2'h1 ? 3'h2 : req_old_meta_coh_state == 2'h0 ? 3'h5 : 3'h0;	// @[Metadata.scala:161:16, Misc.scala:37:36, :55:20, Mux.scala:81:58, NBDcache.scala:170:16]
  assign io_wb_req_bits_way_en = req_way_en;	// @[NBDcache.scala:170:16]
  assign io_probe_rdy = ~idx_match | ~(_io_wb_req_valid_output | _io_probe_rdy_T_2 | _io_meta_write_bits_data_coh_T) & meta_hazard == 2'h0;	// @[Metadata.scala:161:16, NBDcache.scala:174:27, :272:28, :275:{19,30,34,71,86}, package.scala:16:47, :73:59]
endmodule

