/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_core.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_exc.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_func.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_lib.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_mem.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_rch.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_reg.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_rmem.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_rreq.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_rresp.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_rst.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_wch.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_WDT.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_wmem.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_wrapper.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_wreq.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_slave_emb_wresp.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_xram_adapter.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_xram_mon.sv
/nfs/projects/vsa/victord/GuoChuang/BigSoc-v2/work/xaxi4_slave_emb/xaxi4_xram_rlatency_mon.sv
