// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`define XEPIC_P2E
`define XEPIC_XRAM_RTL
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module XilinxVCU118MIGIsland(
  input         clock,
                reset,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_0_id,
  input  [31:0] auto_axi4in_xing_in_aw_mem_0_addr,
  input  [7:0]  auto_axi4in_xing_in_aw_mem_0_len,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_0_size,
  input  [1:0]  auto_axi4in_xing_in_aw_mem_0_burst,
  input         auto_axi4in_xing_in_aw_mem_0_lock,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_0_cache,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_0_prot,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_0_qos,
                auto_axi4in_xing_in_aw_mem_1_id,
  input  [31:0] auto_axi4in_xing_in_aw_mem_1_addr,
  input  [7:0]  auto_axi4in_xing_in_aw_mem_1_len,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_1_size,
  input  [1:0]  auto_axi4in_xing_in_aw_mem_1_burst,
  input         auto_axi4in_xing_in_aw_mem_1_lock,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_1_cache,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_1_prot,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_1_qos,
                auto_axi4in_xing_in_aw_mem_2_id,
  input  [31:0] auto_axi4in_xing_in_aw_mem_2_addr,
  input  [7:0]  auto_axi4in_xing_in_aw_mem_2_len,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_2_size,
  input  [1:0]  auto_axi4in_xing_in_aw_mem_2_burst,
  input         auto_axi4in_xing_in_aw_mem_2_lock,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_2_cache,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_2_prot,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_2_qos,
                auto_axi4in_xing_in_aw_mem_3_id,
  input  [31:0] auto_axi4in_xing_in_aw_mem_3_addr,
  input  [7:0]  auto_axi4in_xing_in_aw_mem_3_len,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_3_size,
  input  [1:0]  auto_axi4in_xing_in_aw_mem_3_burst,
  input         auto_axi4in_xing_in_aw_mem_3_lock,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_3_cache,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_3_prot,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_3_qos,
                auto_axi4in_xing_in_aw_mem_4_id,
  input  [31:0] auto_axi4in_xing_in_aw_mem_4_addr,
  input  [7:0]  auto_axi4in_xing_in_aw_mem_4_len,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_4_size,
  input  [1:0]  auto_axi4in_xing_in_aw_mem_4_burst,
  input         auto_axi4in_xing_in_aw_mem_4_lock,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_4_cache,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_4_prot,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_4_qos,
                auto_axi4in_xing_in_aw_mem_5_id,
  input  [31:0] auto_axi4in_xing_in_aw_mem_5_addr,
  input  [7:0]  auto_axi4in_xing_in_aw_mem_5_len,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_5_size,
  input  [1:0]  auto_axi4in_xing_in_aw_mem_5_burst,
  input         auto_axi4in_xing_in_aw_mem_5_lock,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_5_cache,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_5_prot,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_5_qos,
                auto_axi4in_xing_in_aw_mem_6_id,
  input  [31:0] auto_axi4in_xing_in_aw_mem_6_addr,
  input  [7:0]  auto_axi4in_xing_in_aw_mem_6_len,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_6_size,
  input  [1:0]  auto_axi4in_xing_in_aw_mem_6_burst,
  input         auto_axi4in_xing_in_aw_mem_6_lock,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_6_cache,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_6_prot,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_6_qos,
                auto_axi4in_xing_in_aw_mem_7_id,
  input  [31:0] auto_axi4in_xing_in_aw_mem_7_addr,
  input  [7:0]  auto_axi4in_xing_in_aw_mem_7_len,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_7_size,
  input  [1:0]  auto_axi4in_xing_in_aw_mem_7_burst,
  input         auto_axi4in_xing_in_aw_mem_7_lock,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_7_cache,
  input  [2:0]  auto_axi4in_xing_in_aw_mem_7_prot,
  input  [3:0]  auto_axi4in_xing_in_aw_mem_7_qos,
                auto_axi4in_xing_in_aw_widx,
  input         auto_axi4in_xing_in_aw_safe_widx_valid,
                auto_axi4in_xing_in_aw_safe_source_reset_n,
  input  [63:0] auto_axi4in_xing_in_w_mem_0_data,
  input  [7:0]  auto_axi4in_xing_in_w_mem_0_strb,
  input         auto_axi4in_xing_in_w_mem_0_last,
  input  [63:0] auto_axi4in_xing_in_w_mem_1_data,
  input  [7:0]  auto_axi4in_xing_in_w_mem_1_strb,
  input         auto_axi4in_xing_in_w_mem_1_last,
  input  [63:0] auto_axi4in_xing_in_w_mem_2_data,
  input  [7:0]  auto_axi4in_xing_in_w_mem_2_strb,
  input         auto_axi4in_xing_in_w_mem_2_last,
  input  [63:0] auto_axi4in_xing_in_w_mem_3_data,
  input  [7:0]  auto_axi4in_xing_in_w_mem_3_strb,
  input         auto_axi4in_xing_in_w_mem_3_last,
  input  [63:0] auto_axi4in_xing_in_w_mem_4_data,
  input  [7:0]  auto_axi4in_xing_in_w_mem_4_strb,
  input         auto_axi4in_xing_in_w_mem_4_last,
  input  [63:0] auto_axi4in_xing_in_w_mem_5_data,
  input  [7:0]  auto_axi4in_xing_in_w_mem_5_strb,
  input         auto_axi4in_xing_in_w_mem_5_last,
  input  [63:0] auto_axi4in_xing_in_w_mem_6_data,
  input  [7:0]  auto_axi4in_xing_in_w_mem_6_strb,
  input         auto_axi4in_xing_in_w_mem_6_last,
  input  [63:0] auto_axi4in_xing_in_w_mem_7_data,
  input  [7:0]  auto_axi4in_xing_in_w_mem_7_strb,
  input         auto_axi4in_xing_in_w_mem_7_last,
  input  [3:0]  auto_axi4in_xing_in_w_widx,
  input         auto_axi4in_xing_in_w_safe_widx_valid,
                auto_axi4in_xing_in_w_safe_source_reset_n,
  input  [3:0]  auto_axi4in_xing_in_b_ridx,
  input         auto_axi4in_xing_in_b_safe_ridx_valid,
                auto_axi4in_xing_in_b_safe_sink_reset_n,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_0_id,
  input  [31:0] auto_axi4in_xing_in_ar_mem_0_addr,
  input  [7:0]  auto_axi4in_xing_in_ar_mem_0_len,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_0_size,
  input  [1:0]  auto_axi4in_xing_in_ar_mem_0_burst,
  input         auto_axi4in_xing_in_ar_mem_0_lock,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_0_cache,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_0_prot,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_0_qos,
                auto_axi4in_xing_in_ar_mem_1_id,
  input  [31:0] auto_axi4in_xing_in_ar_mem_1_addr,
  input  [7:0]  auto_axi4in_xing_in_ar_mem_1_len,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_1_size,
  input  [1:0]  auto_axi4in_xing_in_ar_mem_1_burst,
  input         auto_axi4in_xing_in_ar_mem_1_lock,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_1_cache,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_1_prot,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_1_qos,
                auto_axi4in_xing_in_ar_mem_2_id,
  input  [31:0] auto_axi4in_xing_in_ar_mem_2_addr,
  input  [7:0]  auto_axi4in_xing_in_ar_mem_2_len,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_2_size,
  input  [1:0]  auto_axi4in_xing_in_ar_mem_2_burst,
  input         auto_axi4in_xing_in_ar_mem_2_lock,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_2_cache,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_2_prot,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_2_qos,
                auto_axi4in_xing_in_ar_mem_3_id,
  input  [31:0] auto_axi4in_xing_in_ar_mem_3_addr,
  input  [7:0]  auto_axi4in_xing_in_ar_mem_3_len,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_3_size,
  input  [1:0]  auto_axi4in_xing_in_ar_mem_3_burst,
  input         auto_axi4in_xing_in_ar_mem_3_lock,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_3_cache,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_3_prot,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_3_qos,
                auto_axi4in_xing_in_ar_mem_4_id,
  input  [31:0] auto_axi4in_xing_in_ar_mem_4_addr,
  input  [7:0]  auto_axi4in_xing_in_ar_mem_4_len,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_4_size,
  input  [1:0]  auto_axi4in_xing_in_ar_mem_4_burst,
  input         auto_axi4in_xing_in_ar_mem_4_lock,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_4_cache,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_4_prot,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_4_qos,
                auto_axi4in_xing_in_ar_mem_5_id,
  input  [31:0] auto_axi4in_xing_in_ar_mem_5_addr,
  input  [7:0]  auto_axi4in_xing_in_ar_mem_5_len,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_5_size,
  input  [1:0]  auto_axi4in_xing_in_ar_mem_5_burst,
  input         auto_axi4in_xing_in_ar_mem_5_lock,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_5_cache,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_5_prot,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_5_qos,
                auto_axi4in_xing_in_ar_mem_6_id,
  input  [31:0] auto_axi4in_xing_in_ar_mem_6_addr,
  input  [7:0]  auto_axi4in_xing_in_ar_mem_6_len,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_6_size,
  input  [1:0]  auto_axi4in_xing_in_ar_mem_6_burst,
  input         auto_axi4in_xing_in_ar_mem_6_lock,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_6_cache,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_6_prot,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_6_qos,
                auto_axi4in_xing_in_ar_mem_7_id,
  input  [31:0] auto_axi4in_xing_in_ar_mem_7_addr,
  input  [7:0]  auto_axi4in_xing_in_ar_mem_7_len,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_7_size,
  input  [1:0]  auto_axi4in_xing_in_ar_mem_7_burst,
  input         auto_axi4in_xing_in_ar_mem_7_lock,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_7_cache,
  input  [2:0]  auto_axi4in_xing_in_ar_mem_7_prot,
  input  [3:0]  auto_axi4in_xing_in_ar_mem_7_qos,
                auto_axi4in_xing_in_ar_widx,
  input         auto_axi4in_xing_in_ar_safe_widx_valid,
                auto_axi4in_xing_in_ar_safe_source_reset_n,
  input  [3:0]  auto_axi4in_xing_in_r_ridx,
  input         auto_axi4in_xing_in_r_safe_ridx_valid,
                auto_axi4in_xing_in_r_safe_sink_reset_n,
  inout  [63:0] io_port_c0_ddr4_dq,
  inout  [7:0]  io_port_c0_ddr4_dqs_c,
                io_port_c0_ddr4_dqs_t,
                io_port_c0_ddr4_dm_dbi_n,
  input         io_port_c0_sys_clk_i,
                io_port_c0_ddr4_aresetn,
                io_port_sys_rst,
  output [3:0]  auto_axi4in_xing_in_aw_ridx,
  output        auto_axi4in_xing_in_aw_safe_ridx_valid,
                auto_axi4in_xing_in_aw_safe_sink_reset_n,
  output [3:0]  auto_axi4in_xing_in_w_ridx,
  output        auto_axi4in_xing_in_w_safe_ridx_valid,
                auto_axi4in_xing_in_w_safe_sink_reset_n,
  output [3:0]  auto_axi4in_xing_in_b_mem_0_id,
  output [1:0]  auto_axi4in_xing_in_b_mem_0_resp,
  output [3:0]  auto_axi4in_xing_in_b_mem_1_id,
  output [1:0]  auto_axi4in_xing_in_b_mem_1_resp,
  output [3:0]  auto_axi4in_xing_in_b_mem_2_id,
  output [1:0]  auto_axi4in_xing_in_b_mem_2_resp,
  output [3:0]  auto_axi4in_xing_in_b_mem_3_id,
  output [1:0]  auto_axi4in_xing_in_b_mem_3_resp,
  output [3:0]  auto_axi4in_xing_in_b_mem_4_id,
  output [1:0]  auto_axi4in_xing_in_b_mem_4_resp,
  output [3:0]  auto_axi4in_xing_in_b_mem_5_id,
  output [1:0]  auto_axi4in_xing_in_b_mem_5_resp,
  output [3:0]  auto_axi4in_xing_in_b_mem_6_id,
  output [1:0]  auto_axi4in_xing_in_b_mem_6_resp,
  output [3:0]  auto_axi4in_xing_in_b_mem_7_id,
  output [1:0]  auto_axi4in_xing_in_b_mem_7_resp,
  output [3:0]  auto_axi4in_xing_in_b_widx,
  output        auto_axi4in_xing_in_b_safe_widx_valid,
                auto_axi4in_xing_in_b_safe_source_reset_n,
  output [3:0]  auto_axi4in_xing_in_ar_ridx,
  output        auto_axi4in_xing_in_ar_safe_ridx_valid,
                auto_axi4in_xing_in_ar_safe_sink_reset_n,
  output [3:0]  auto_axi4in_xing_in_r_mem_0_id,
  output [63:0] auto_axi4in_xing_in_r_mem_0_data,
  output [1:0]  auto_axi4in_xing_in_r_mem_0_resp,
  output        auto_axi4in_xing_in_r_mem_0_last,
  output [3:0]  auto_axi4in_xing_in_r_mem_1_id,
  output [63:0] auto_axi4in_xing_in_r_mem_1_data,
  output [1:0]  auto_axi4in_xing_in_r_mem_1_resp,
  output        auto_axi4in_xing_in_r_mem_1_last,
  output [3:0]  auto_axi4in_xing_in_r_mem_2_id,
  output [63:0] auto_axi4in_xing_in_r_mem_2_data,
  output [1:0]  auto_axi4in_xing_in_r_mem_2_resp,
  output        auto_axi4in_xing_in_r_mem_2_last,
  output [3:0]  auto_axi4in_xing_in_r_mem_3_id,
  output [63:0] auto_axi4in_xing_in_r_mem_3_data,
  output [1:0]  auto_axi4in_xing_in_r_mem_3_resp,
  output        auto_axi4in_xing_in_r_mem_3_last,
  output [3:0]  auto_axi4in_xing_in_r_mem_4_id,
  output [63:0] auto_axi4in_xing_in_r_mem_4_data,
  output [1:0]  auto_axi4in_xing_in_r_mem_4_resp,
  output        auto_axi4in_xing_in_r_mem_4_last,
  output [3:0]  auto_axi4in_xing_in_r_mem_5_id,
  output [63:0] auto_axi4in_xing_in_r_mem_5_data,
  output [1:0]  auto_axi4in_xing_in_r_mem_5_resp,
  output        auto_axi4in_xing_in_r_mem_5_last,
  output [3:0]  auto_axi4in_xing_in_r_mem_6_id,
  output [63:0] auto_axi4in_xing_in_r_mem_6_data,
  output [1:0]  auto_axi4in_xing_in_r_mem_6_resp,
  output        auto_axi4in_xing_in_r_mem_6_last,
  output [3:0]  auto_axi4in_xing_in_r_mem_7_id,
  output [63:0] auto_axi4in_xing_in_r_mem_7_data,
  output [1:0]  auto_axi4in_xing_in_r_mem_7_resp,
  output        auto_axi4in_xing_in_r_mem_7_last,
  output [3:0]  auto_axi4in_xing_in_r_widx,
  output        auto_axi4in_xing_in_r_safe_widx_valid,
                auto_axi4in_xing_in_r_safe_source_reset_n,
  output [16:0] io_port_c0_ddr4_adr,
  output        io_port_c0_ddr4_bg,
  output [1:0]  io_port_c0_ddr4_ba,
  output        io_port_c0_ddr4_reset_n,
                io_port_c0_ddr4_act_n,
                io_port_c0_ddr4_ck_c,
                io_port_c0_ddr4_ck_t,
                io_port_c0_ddr4_cke,
                io_port_c0_ddr4_cs_n,
                io_port_c0_ddr4_odt,
                io_port_c0_ddr4_ui_clk,
                io_port_c0_ddr4_ui_clk_sync_rst
);

  wire        _blackbox_c0_ddr4_s_axi_awready;	// @[XilinxVCU118MIG.scala:51:26]
  wire        _blackbox_c0_ddr4_s_axi_wready;	// @[XilinxVCU118MIG.scala:51:26]
  wire [3:0]  _blackbox_c0_ddr4_s_axi_bid;	// @[XilinxVCU118MIG.scala:51:26]
  wire [1:0]  _blackbox_c0_ddr4_s_axi_bresp;	// @[XilinxVCU118MIG.scala:51:26]
  wire        _blackbox_c0_ddr4_s_axi_bvalid;	// @[XilinxVCU118MIG.scala:51:26]
  wire        _blackbox_c0_ddr4_s_axi_arready;	// @[XilinxVCU118MIG.scala:51:26]
  wire [3:0]  _blackbox_c0_ddr4_s_axi_rid;	// @[XilinxVCU118MIG.scala:51:26]
  wire [63:0] _blackbox_c0_ddr4_s_axi_rdata;	// @[XilinxVCU118MIG.scala:51:26]
  wire [1:0]  _blackbox_c0_ddr4_s_axi_rresp;	// @[XilinxVCU118MIG.scala:51:26]
  wire        _blackbox_c0_ddr4_s_axi_rlast;	// @[XilinxVCU118MIG.scala:51:26]
  wire        _blackbox_c0_ddr4_s_axi_rvalid;	// @[XilinxVCU118MIG.scala:51:26]
  wire        _axi4asink_auto_out_aw_valid;	// @[AsyncCrossing.scala:72:31]
  wire [3:0]  _axi4asink_auto_out_aw_bits_id;	// @[AsyncCrossing.scala:72:31]
  wire [31:0] _axi4asink_auto_out_aw_bits_addr;	// @[AsyncCrossing.scala:72:31]
  wire [7:0]  _axi4asink_auto_out_aw_bits_len;	// @[AsyncCrossing.scala:72:31]
  wire [2:0]  _axi4asink_auto_out_aw_bits_size;	// @[AsyncCrossing.scala:72:31]
  wire [1:0]  _axi4asink_auto_out_aw_bits_burst;	// @[AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_aw_bits_lock;	// @[AsyncCrossing.scala:72:31]
  wire [2:0]  _axi4asink_auto_out_aw_bits_prot;	// @[AsyncCrossing.scala:72:31]
  wire [3:0]  _axi4asink_auto_out_aw_bits_qos;	// @[AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_w_valid;	// @[AsyncCrossing.scala:72:31]
  wire [63:0] _axi4asink_auto_out_w_bits_data;	// @[AsyncCrossing.scala:72:31]
  wire [7:0]  _axi4asink_auto_out_w_bits_strb;	// @[AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_w_bits_last;	// @[AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_b_ready;	// @[AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_ar_valid;	// @[AsyncCrossing.scala:72:31]
  wire [3:0]  _axi4asink_auto_out_ar_bits_id;	// @[AsyncCrossing.scala:72:31]
  wire [31:0] _axi4asink_auto_out_ar_bits_addr;	// @[AsyncCrossing.scala:72:31]
  wire [7:0]  _axi4asink_auto_out_ar_bits_len;	// @[AsyncCrossing.scala:72:31]
  wire [2:0]  _axi4asink_auto_out_ar_bits_size;	// @[AsyncCrossing.scala:72:31]
  wire [1:0]  _axi4asink_auto_out_ar_bits_burst;	// @[AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_ar_bits_lock;	// @[AsyncCrossing.scala:72:31]
  wire [2:0]  _axi4asink_auto_out_ar_bits_prot;	// @[AsyncCrossing.scala:72:31]
  wire [3:0]  _axi4asink_auto_out_ar_bits_qos;	// @[AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_r_ready;	// @[AsyncCrossing.scala:72:31]
  wire        com_reset;
  wire        _blackbox_c0_init_calib_complete;	// @[XilinxVCU118MIG.scala:51:26]
  assign com_reset = reset | (~_blackbox_c0_init_calib_complete);
  AXI4AsyncCrossingSink axi4asink (	// @[AsyncCrossing.scala:72:31]
    .clock                          (clock),
    .reset                          (com_reset),
    .auto_in_aw_mem_0_id            (auto_axi4in_xing_in_aw_mem_0_id),
    .auto_in_aw_mem_0_addr          (auto_axi4in_xing_in_aw_mem_0_addr),
    .auto_in_aw_mem_0_len           (auto_axi4in_xing_in_aw_mem_0_len),
    .auto_in_aw_mem_0_size          (auto_axi4in_xing_in_aw_mem_0_size),
    .auto_in_aw_mem_0_burst         (auto_axi4in_xing_in_aw_mem_0_burst),
    .auto_in_aw_mem_0_lock          (auto_axi4in_xing_in_aw_mem_0_lock),
    .auto_in_aw_mem_0_cache         (auto_axi4in_xing_in_aw_mem_0_cache),
    .auto_in_aw_mem_0_prot          (auto_axi4in_xing_in_aw_mem_0_prot),
    .auto_in_aw_mem_0_qos           (auto_axi4in_xing_in_aw_mem_0_qos),
    .auto_in_aw_mem_1_id            (auto_axi4in_xing_in_aw_mem_1_id),
    .auto_in_aw_mem_1_addr          (auto_axi4in_xing_in_aw_mem_1_addr),
    .auto_in_aw_mem_1_len           (auto_axi4in_xing_in_aw_mem_1_len),
    .auto_in_aw_mem_1_size          (auto_axi4in_xing_in_aw_mem_1_size),
    .auto_in_aw_mem_1_burst         (auto_axi4in_xing_in_aw_mem_1_burst),
    .auto_in_aw_mem_1_lock          (auto_axi4in_xing_in_aw_mem_1_lock),
    .auto_in_aw_mem_1_cache         (auto_axi4in_xing_in_aw_mem_1_cache),
    .auto_in_aw_mem_1_prot          (auto_axi4in_xing_in_aw_mem_1_prot),
    .auto_in_aw_mem_1_qos           (auto_axi4in_xing_in_aw_mem_1_qos),
    .auto_in_aw_mem_2_id            (auto_axi4in_xing_in_aw_mem_2_id),
    .auto_in_aw_mem_2_addr          (auto_axi4in_xing_in_aw_mem_2_addr),
    .auto_in_aw_mem_2_len           (auto_axi4in_xing_in_aw_mem_2_len),
    .auto_in_aw_mem_2_size          (auto_axi4in_xing_in_aw_mem_2_size),
    .auto_in_aw_mem_2_burst         (auto_axi4in_xing_in_aw_mem_2_burst),
    .auto_in_aw_mem_2_lock          (auto_axi4in_xing_in_aw_mem_2_lock),
    .auto_in_aw_mem_2_cache         (auto_axi4in_xing_in_aw_mem_2_cache),
    .auto_in_aw_mem_2_prot          (auto_axi4in_xing_in_aw_mem_2_prot),
    .auto_in_aw_mem_2_qos           (auto_axi4in_xing_in_aw_mem_2_qos),
    .auto_in_aw_mem_3_id            (auto_axi4in_xing_in_aw_mem_3_id),
    .auto_in_aw_mem_3_addr          (auto_axi4in_xing_in_aw_mem_3_addr),
    .auto_in_aw_mem_3_len           (auto_axi4in_xing_in_aw_mem_3_len),
    .auto_in_aw_mem_3_size          (auto_axi4in_xing_in_aw_mem_3_size),
    .auto_in_aw_mem_3_burst         (auto_axi4in_xing_in_aw_mem_3_burst),
    .auto_in_aw_mem_3_lock          (auto_axi4in_xing_in_aw_mem_3_lock),
    .auto_in_aw_mem_3_cache         (auto_axi4in_xing_in_aw_mem_3_cache),
    .auto_in_aw_mem_3_prot          (auto_axi4in_xing_in_aw_mem_3_prot),
    .auto_in_aw_mem_3_qos           (auto_axi4in_xing_in_aw_mem_3_qos),
    .auto_in_aw_mem_4_id            (auto_axi4in_xing_in_aw_mem_4_id),
    .auto_in_aw_mem_4_addr          (auto_axi4in_xing_in_aw_mem_4_addr),
    .auto_in_aw_mem_4_len           (auto_axi4in_xing_in_aw_mem_4_len),
    .auto_in_aw_mem_4_size          (auto_axi4in_xing_in_aw_mem_4_size),
    .auto_in_aw_mem_4_burst         (auto_axi4in_xing_in_aw_mem_4_burst),
    .auto_in_aw_mem_4_lock          (auto_axi4in_xing_in_aw_mem_4_lock),
    .auto_in_aw_mem_4_cache         (auto_axi4in_xing_in_aw_mem_4_cache),
    .auto_in_aw_mem_4_prot          (auto_axi4in_xing_in_aw_mem_4_prot),
    .auto_in_aw_mem_4_qos           (auto_axi4in_xing_in_aw_mem_4_qos),
    .auto_in_aw_mem_5_id            (auto_axi4in_xing_in_aw_mem_5_id),
    .auto_in_aw_mem_5_addr          (auto_axi4in_xing_in_aw_mem_5_addr),
    .auto_in_aw_mem_5_len           (auto_axi4in_xing_in_aw_mem_5_len),
    .auto_in_aw_mem_5_size          (auto_axi4in_xing_in_aw_mem_5_size),
    .auto_in_aw_mem_5_burst         (auto_axi4in_xing_in_aw_mem_5_burst),
    .auto_in_aw_mem_5_lock          (auto_axi4in_xing_in_aw_mem_5_lock),
    .auto_in_aw_mem_5_cache         (auto_axi4in_xing_in_aw_mem_5_cache),
    .auto_in_aw_mem_5_prot          (auto_axi4in_xing_in_aw_mem_5_prot),
    .auto_in_aw_mem_5_qos           (auto_axi4in_xing_in_aw_mem_5_qos),
    .auto_in_aw_mem_6_id            (auto_axi4in_xing_in_aw_mem_6_id),
    .auto_in_aw_mem_6_addr          (auto_axi4in_xing_in_aw_mem_6_addr),
    .auto_in_aw_mem_6_len           (auto_axi4in_xing_in_aw_mem_6_len),
    .auto_in_aw_mem_6_size          (auto_axi4in_xing_in_aw_mem_6_size),
    .auto_in_aw_mem_6_burst         (auto_axi4in_xing_in_aw_mem_6_burst),
    .auto_in_aw_mem_6_lock          (auto_axi4in_xing_in_aw_mem_6_lock),
    .auto_in_aw_mem_6_cache         (auto_axi4in_xing_in_aw_mem_6_cache),
    .auto_in_aw_mem_6_prot          (auto_axi4in_xing_in_aw_mem_6_prot),
    .auto_in_aw_mem_6_qos           (auto_axi4in_xing_in_aw_mem_6_qos),
    .auto_in_aw_mem_7_id            (auto_axi4in_xing_in_aw_mem_7_id),
    .auto_in_aw_mem_7_addr          (auto_axi4in_xing_in_aw_mem_7_addr),
    .auto_in_aw_mem_7_len           (auto_axi4in_xing_in_aw_mem_7_len),
    .auto_in_aw_mem_7_size          (auto_axi4in_xing_in_aw_mem_7_size),
    .auto_in_aw_mem_7_burst         (auto_axi4in_xing_in_aw_mem_7_burst),
    .auto_in_aw_mem_7_lock          (auto_axi4in_xing_in_aw_mem_7_lock),
    .auto_in_aw_mem_7_cache         (auto_axi4in_xing_in_aw_mem_7_cache),
    .auto_in_aw_mem_7_prot          (auto_axi4in_xing_in_aw_mem_7_prot),
    .auto_in_aw_mem_7_qos           (auto_axi4in_xing_in_aw_mem_7_qos),
    .auto_in_aw_widx                (auto_axi4in_xing_in_aw_widx),
    .auto_in_aw_safe_widx_valid     (auto_axi4in_xing_in_aw_safe_widx_valid),
    .auto_in_aw_safe_source_reset_n (auto_axi4in_xing_in_aw_safe_source_reset_n),
    .auto_in_w_mem_0_data           (auto_axi4in_xing_in_w_mem_0_data),
    .auto_in_w_mem_0_strb           (auto_axi4in_xing_in_w_mem_0_strb),
    .auto_in_w_mem_0_last           (auto_axi4in_xing_in_w_mem_0_last),
    .auto_in_w_mem_1_data           (auto_axi4in_xing_in_w_mem_1_data),
    .auto_in_w_mem_1_strb           (auto_axi4in_xing_in_w_mem_1_strb),
    .auto_in_w_mem_1_last           (auto_axi4in_xing_in_w_mem_1_last),
    .auto_in_w_mem_2_data           (auto_axi4in_xing_in_w_mem_2_data),
    .auto_in_w_mem_2_strb           (auto_axi4in_xing_in_w_mem_2_strb),
    .auto_in_w_mem_2_last           (auto_axi4in_xing_in_w_mem_2_last),
    .auto_in_w_mem_3_data           (auto_axi4in_xing_in_w_mem_3_data),
    .auto_in_w_mem_3_strb           (auto_axi4in_xing_in_w_mem_3_strb),
    .auto_in_w_mem_3_last           (auto_axi4in_xing_in_w_mem_3_last),
    .auto_in_w_mem_4_data           (auto_axi4in_xing_in_w_mem_4_data),
    .auto_in_w_mem_4_strb           (auto_axi4in_xing_in_w_mem_4_strb),
    .auto_in_w_mem_4_last           (auto_axi4in_xing_in_w_mem_4_last),
    .auto_in_w_mem_5_data           (auto_axi4in_xing_in_w_mem_5_data),
    .auto_in_w_mem_5_strb           (auto_axi4in_xing_in_w_mem_5_strb),
    .auto_in_w_mem_5_last           (auto_axi4in_xing_in_w_mem_5_last),
    .auto_in_w_mem_6_data           (auto_axi4in_xing_in_w_mem_6_data),
    .auto_in_w_mem_6_strb           (auto_axi4in_xing_in_w_mem_6_strb),
    .auto_in_w_mem_6_last           (auto_axi4in_xing_in_w_mem_6_last),
    .auto_in_w_mem_7_data           (auto_axi4in_xing_in_w_mem_7_data),
    .auto_in_w_mem_7_strb           (auto_axi4in_xing_in_w_mem_7_strb),
    .auto_in_w_mem_7_last           (auto_axi4in_xing_in_w_mem_7_last),
    .auto_in_w_widx                 (auto_axi4in_xing_in_w_widx),
    .auto_in_w_safe_widx_valid      (auto_axi4in_xing_in_w_safe_widx_valid),
    .auto_in_w_safe_source_reset_n  (auto_axi4in_xing_in_w_safe_source_reset_n),
    .auto_in_b_ridx                 (auto_axi4in_xing_in_b_ridx),
    .auto_in_b_safe_ridx_valid      (auto_axi4in_xing_in_b_safe_ridx_valid),
    .auto_in_b_safe_sink_reset_n    (auto_axi4in_xing_in_b_safe_sink_reset_n),
    .auto_in_ar_mem_0_id            (auto_axi4in_xing_in_ar_mem_0_id),
    .auto_in_ar_mem_0_addr          (auto_axi4in_xing_in_ar_mem_0_addr),
    .auto_in_ar_mem_0_len           (auto_axi4in_xing_in_ar_mem_0_len),
    .auto_in_ar_mem_0_size          (auto_axi4in_xing_in_ar_mem_0_size),
    .auto_in_ar_mem_0_burst         (auto_axi4in_xing_in_ar_mem_0_burst),
    .auto_in_ar_mem_0_lock          (auto_axi4in_xing_in_ar_mem_0_lock),
    .auto_in_ar_mem_0_cache         (auto_axi4in_xing_in_ar_mem_0_cache),
    .auto_in_ar_mem_0_prot          (auto_axi4in_xing_in_ar_mem_0_prot),
    .auto_in_ar_mem_0_qos           (auto_axi4in_xing_in_ar_mem_0_qos),
    .auto_in_ar_mem_1_id            (auto_axi4in_xing_in_ar_mem_1_id),
    .auto_in_ar_mem_1_addr          (auto_axi4in_xing_in_ar_mem_1_addr),
    .auto_in_ar_mem_1_len           (auto_axi4in_xing_in_ar_mem_1_len),
    .auto_in_ar_mem_1_size          (auto_axi4in_xing_in_ar_mem_1_size),
    .auto_in_ar_mem_1_burst         (auto_axi4in_xing_in_ar_mem_1_burst),
    .auto_in_ar_mem_1_lock          (auto_axi4in_xing_in_ar_mem_1_lock),
    .auto_in_ar_mem_1_cache         (auto_axi4in_xing_in_ar_mem_1_cache),
    .auto_in_ar_mem_1_prot          (auto_axi4in_xing_in_ar_mem_1_prot),
    .auto_in_ar_mem_1_qos           (auto_axi4in_xing_in_ar_mem_1_qos),
    .auto_in_ar_mem_2_id            (auto_axi4in_xing_in_ar_mem_2_id),
    .auto_in_ar_mem_2_addr          (auto_axi4in_xing_in_ar_mem_2_addr),
    .auto_in_ar_mem_2_len           (auto_axi4in_xing_in_ar_mem_2_len),
    .auto_in_ar_mem_2_size          (auto_axi4in_xing_in_ar_mem_2_size),
    .auto_in_ar_mem_2_burst         (auto_axi4in_xing_in_ar_mem_2_burst),
    .auto_in_ar_mem_2_lock          (auto_axi4in_xing_in_ar_mem_2_lock),
    .auto_in_ar_mem_2_cache         (auto_axi4in_xing_in_ar_mem_2_cache),
    .auto_in_ar_mem_2_prot          (auto_axi4in_xing_in_ar_mem_2_prot),
    .auto_in_ar_mem_2_qos           (auto_axi4in_xing_in_ar_mem_2_qos),
    .auto_in_ar_mem_3_id            (auto_axi4in_xing_in_ar_mem_3_id),
    .auto_in_ar_mem_3_addr          (auto_axi4in_xing_in_ar_mem_3_addr),
    .auto_in_ar_mem_3_len           (auto_axi4in_xing_in_ar_mem_3_len),
    .auto_in_ar_mem_3_size          (auto_axi4in_xing_in_ar_mem_3_size),
    .auto_in_ar_mem_3_burst         (auto_axi4in_xing_in_ar_mem_3_burst),
    .auto_in_ar_mem_3_lock          (auto_axi4in_xing_in_ar_mem_3_lock),
    .auto_in_ar_mem_3_cache         (auto_axi4in_xing_in_ar_mem_3_cache),
    .auto_in_ar_mem_3_prot          (auto_axi4in_xing_in_ar_mem_3_prot),
    .auto_in_ar_mem_3_qos           (auto_axi4in_xing_in_ar_mem_3_qos),
    .auto_in_ar_mem_4_id            (auto_axi4in_xing_in_ar_mem_4_id),
    .auto_in_ar_mem_4_addr          (auto_axi4in_xing_in_ar_mem_4_addr),
    .auto_in_ar_mem_4_len           (auto_axi4in_xing_in_ar_mem_4_len),
    .auto_in_ar_mem_4_size          (auto_axi4in_xing_in_ar_mem_4_size),
    .auto_in_ar_mem_4_burst         (auto_axi4in_xing_in_ar_mem_4_burst),
    .auto_in_ar_mem_4_lock          (auto_axi4in_xing_in_ar_mem_4_lock),
    .auto_in_ar_mem_4_cache         (auto_axi4in_xing_in_ar_mem_4_cache),
    .auto_in_ar_mem_4_prot          (auto_axi4in_xing_in_ar_mem_4_prot),
    .auto_in_ar_mem_4_qos           (auto_axi4in_xing_in_ar_mem_4_qos),
    .auto_in_ar_mem_5_id            (auto_axi4in_xing_in_ar_mem_5_id),
    .auto_in_ar_mem_5_addr          (auto_axi4in_xing_in_ar_mem_5_addr),
    .auto_in_ar_mem_5_len           (auto_axi4in_xing_in_ar_mem_5_len),
    .auto_in_ar_mem_5_size          (auto_axi4in_xing_in_ar_mem_5_size),
    .auto_in_ar_mem_5_burst         (auto_axi4in_xing_in_ar_mem_5_burst),
    .auto_in_ar_mem_5_lock          (auto_axi4in_xing_in_ar_mem_5_lock),
    .auto_in_ar_mem_5_cache         (auto_axi4in_xing_in_ar_mem_5_cache),
    .auto_in_ar_mem_5_prot          (auto_axi4in_xing_in_ar_mem_5_prot),
    .auto_in_ar_mem_5_qos           (auto_axi4in_xing_in_ar_mem_5_qos),
    .auto_in_ar_mem_6_id            (auto_axi4in_xing_in_ar_mem_6_id),
    .auto_in_ar_mem_6_addr          (auto_axi4in_xing_in_ar_mem_6_addr),
    .auto_in_ar_mem_6_len           (auto_axi4in_xing_in_ar_mem_6_len),
    .auto_in_ar_mem_6_size          (auto_axi4in_xing_in_ar_mem_6_size),
    .auto_in_ar_mem_6_burst         (auto_axi4in_xing_in_ar_mem_6_burst),
    .auto_in_ar_mem_6_lock          (auto_axi4in_xing_in_ar_mem_6_lock),
    .auto_in_ar_mem_6_cache         (auto_axi4in_xing_in_ar_mem_6_cache),
    .auto_in_ar_mem_6_prot          (auto_axi4in_xing_in_ar_mem_6_prot),
    .auto_in_ar_mem_6_qos           (auto_axi4in_xing_in_ar_mem_6_qos),
    .auto_in_ar_mem_7_id            (auto_axi4in_xing_in_ar_mem_7_id),
    .auto_in_ar_mem_7_addr          (auto_axi4in_xing_in_ar_mem_7_addr),
    .auto_in_ar_mem_7_len           (auto_axi4in_xing_in_ar_mem_7_len),
    .auto_in_ar_mem_7_size          (auto_axi4in_xing_in_ar_mem_7_size),
    .auto_in_ar_mem_7_burst         (auto_axi4in_xing_in_ar_mem_7_burst),
    .auto_in_ar_mem_7_lock          (auto_axi4in_xing_in_ar_mem_7_lock),
    .auto_in_ar_mem_7_cache         (auto_axi4in_xing_in_ar_mem_7_cache),
    .auto_in_ar_mem_7_prot          (auto_axi4in_xing_in_ar_mem_7_prot),
    .auto_in_ar_mem_7_qos           (auto_axi4in_xing_in_ar_mem_7_qos),
    .auto_in_ar_widx                (auto_axi4in_xing_in_ar_widx),
    .auto_in_ar_safe_widx_valid     (auto_axi4in_xing_in_ar_safe_widx_valid),
    .auto_in_ar_safe_source_reset_n (auto_axi4in_xing_in_ar_safe_source_reset_n),
    .auto_in_r_ridx                 (auto_axi4in_xing_in_r_ridx),
    .auto_in_r_safe_ridx_valid      (auto_axi4in_xing_in_r_safe_ridx_valid),
    .auto_in_r_safe_sink_reset_n    (auto_axi4in_xing_in_r_safe_sink_reset_n),
    .auto_out_aw_ready              (_blackbox_c0_ddr4_s_axi_awready),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_out_w_ready               (_blackbox_c0_ddr4_s_axi_wready),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_out_b_valid               (_blackbox_c0_ddr4_s_axi_bvalid),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_out_b_bits_id             (_blackbox_c0_ddr4_s_axi_bid),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_out_b_bits_resp           (_blackbox_c0_ddr4_s_axi_bresp),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_out_ar_ready              (_blackbox_c0_ddr4_s_axi_arready),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_out_r_valid               (_blackbox_c0_ddr4_s_axi_rvalid),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_out_r_bits_id             (_blackbox_c0_ddr4_s_axi_rid),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_out_r_bits_data           (_blackbox_c0_ddr4_s_axi_rdata),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_out_r_bits_resp           (_blackbox_c0_ddr4_s_axi_rresp),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_out_r_bits_last           (_blackbox_c0_ddr4_s_axi_rlast),	// @[XilinxVCU118MIG.scala:51:26]
    .auto_in_aw_ridx                (auto_axi4in_xing_in_aw_ridx),
    .auto_in_aw_safe_ridx_valid     (auto_axi4in_xing_in_aw_safe_ridx_valid),
    .auto_in_aw_safe_sink_reset_n   (auto_axi4in_xing_in_aw_safe_sink_reset_n),
    .auto_in_w_ridx                 (auto_axi4in_xing_in_w_ridx),
    .auto_in_w_safe_ridx_valid      (auto_axi4in_xing_in_w_safe_ridx_valid),
    .auto_in_w_safe_sink_reset_n    (auto_axi4in_xing_in_w_safe_sink_reset_n),
    .auto_in_b_mem_0_id             (auto_axi4in_xing_in_b_mem_0_id),
    .auto_in_b_mem_0_resp           (auto_axi4in_xing_in_b_mem_0_resp),
    .auto_in_b_mem_1_id             (auto_axi4in_xing_in_b_mem_1_id),
    .auto_in_b_mem_1_resp           (auto_axi4in_xing_in_b_mem_1_resp),
    .auto_in_b_mem_2_id             (auto_axi4in_xing_in_b_mem_2_id),
    .auto_in_b_mem_2_resp           (auto_axi4in_xing_in_b_mem_2_resp),
    .auto_in_b_mem_3_id             (auto_axi4in_xing_in_b_mem_3_id),
    .auto_in_b_mem_3_resp           (auto_axi4in_xing_in_b_mem_3_resp),
    .auto_in_b_mem_4_id             (auto_axi4in_xing_in_b_mem_4_id),
    .auto_in_b_mem_4_resp           (auto_axi4in_xing_in_b_mem_4_resp),
    .auto_in_b_mem_5_id             (auto_axi4in_xing_in_b_mem_5_id),
    .auto_in_b_mem_5_resp           (auto_axi4in_xing_in_b_mem_5_resp),
    .auto_in_b_mem_6_id             (auto_axi4in_xing_in_b_mem_6_id),
    .auto_in_b_mem_6_resp           (auto_axi4in_xing_in_b_mem_6_resp),
    .auto_in_b_mem_7_id             (auto_axi4in_xing_in_b_mem_7_id),
    .auto_in_b_mem_7_resp           (auto_axi4in_xing_in_b_mem_7_resp),
    .auto_in_b_widx                 (auto_axi4in_xing_in_b_widx),
    .auto_in_b_safe_widx_valid      (auto_axi4in_xing_in_b_safe_widx_valid),
    .auto_in_b_safe_source_reset_n  (auto_axi4in_xing_in_b_safe_source_reset_n),
    .auto_in_ar_ridx                (auto_axi4in_xing_in_ar_ridx),
    .auto_in_ar_safe_ridx_valid     (auto_axi4in_xing_in_ar_safe_ridx_valid),
    .auto_in_ar_safe_sink_reset_n   (auto_axi4in_xing_in_ar_safe_sink_reset_n),
    .auto_in_r_mem_0_id             (auto_axi4in_xing_in_r_mem_0_id),
    .auto_in_r_mem_0_data           (auto_axi4in_xing_in_r_mem_0_data),
    .auto_in_r_mem_0_resp           (auto_axi4in_xing_in_r_mem_0_resp),
    .auto_in_r_mem_0_last           (auto_axi4in_xing_in_r_mem_0_last),
    .auto_in_r_mem_1_id             (auto_axi4in_xing_in_r_mem_1_id),
    .auto_in_r_mem_1_data           (auto_axi4in_xing_in_r_mem_1_data),
    .auto_in_r_mem_1_resp           (auto_axi4in_xing_in_r_mem_1_resp),
    .auto_in_r_mem_1_last           (auto_axi4in_xing_in_r_mem_1_last),
    .auto_in_r_mem_2_id             (auto_axi4in_xing_in_r_mem_2_id),
    .auto_in_r_mem_2_data           (auto_axi4in_xing_in_r_mem_2_data),
    .auto_in_r_mem_2_resp           (auto_axi4in_xing_in_r_mem_2_resp),
    .auto_in_r_mem_2_last           (auto_axi4in_xing_in_r_mem_2_last),
    .auto_in_r_mem_3_id             (auto_axi4in_xing_in_r_mem_3_id),
    .auto_in_r_mem_3_data           (auto_axi4in_xing_in_r_mem_3_data),
    .auto_in_r_mem_3_resp           (auto_axi4in_xing_in_r_mem_3_resp),
    .auto_in_r_mem_3_last           (auto_axi4in_xing_in_r_mem_3_last),
    .auto_in_r_mem_4_id             (auto_axi4in_xing_in_r_mem_4_id),
    .auto_in_r_mem_4_data           (auto_axi4in_xing_in_r_mem_4_data),
    .auto_in_r_mem_4_resp           (auto_axi4in_xing_in_r_mem_4_resp),
    .auto_in_r_mem_4_last           (auto_axi4in_xing_in_r_mem_4_last),
    .auto_in_r_mem_5_id             (auto_axi4in_xing_in_r_mem_5_id),
    .auto_in_r_mem_5_data           (auto_axi4in_xing_in_r_mem_5_data),
    .auto_in_r_mem_5_resp           (auto_axi4in_xing_in_r_mem_5_resp),
    .auto_in_r_mem_5_last           (auto_axi4in_xing_in_r_mem_5_last),
    .auto_in_r_mem_6_id             (auto_axi4in_xing_in_r_mem_6_id),
    .auto_in_r_mem_6_data           (auto_axi4in_xing_in_r_mem_6_data),
    .auto_in_r_mem_6_resp           (auto_axi4in_xing_in_r_mem_6_resp),
    .auto_in_r_mem_6_last           (auto_axi4in_xing_in_r_mem_6_last),
    .auto_in_r_mem_7_id             (auto_axi4in_xing_in_r_mem_7_id),
    .auto_in_r_mem_7_data           (auto_axi4in_xing_in_r_mem_7_data),
    .auto_in_r_mem_7_resp           (auto_axi4in_xing_in_r_mem_7_resp),
    .auto_in_r_mem_7_last           (auto_axi4in_xing_in_r_mem_7_last),
    .auto_in_r_widx                 (auto_axi4in_xing_in_r_widx),
    .auto_in_r_safe_widx_valid      (auto_axi4in_xing_in_r_safe_widx_valid),
    .auto_in_r_safe_source_reset_n  (auto_axi4in_xing_in_r_safe_source_reset_n),
    .auto_out_aw_valid              (_axi4asink_auto_out_aw_valid),
    .auto_out_aw_bits_id            (_axi4asink_auto_out_aw_bits_id),
    .auto_out_aw_bits_addr          (_axi4asink_auto_out_aw_bits_addr),
    .auto_out_aw_bits_len           (_axi4asink_auto_out_aw_bits_len),
    .auto_out_aw_bits_size          (_axi4asink_auto_out_aw_bits_size),
    .auto_out_aw_bits_burst         (_axi4asink_auto_out_aw_bits_burst),
    .auto_out_aw_bits_lock          (_axi4asink_auto_out_aw_bits_lock),
    .auto_out_aw_bits_prot          (_axi4asink_auto_out_aw_bits_prot),
    .auto_out_aw_bits_qos           (_axi4asink_auto_out_aw_bits_qos),
    .auto_out_w_valid               (_axi4asink_auto_out_w_valid),
    .auto_out_w_bits_data           (_axi4asink_auto_out_w_bits_data),
    .auto_out_w_bits_strb           (_axi4asink_auto_out_w_bits_strb),
    .auto_out_w_bits_last           (_axi4asink_auto_out_w_bits_last),
    .auto_out_b_ready               (_axi4asink_auto_out_b_ready),
    .auto_out_ar_valid              (_axi4asink_auto_out_ar_valid),
    .auto_out_ar_bits_id            (_axi4asink_auto_out_ar_bits_id),
    .auto_out_ar_bits_addr          (_axi4asink_auto_out_ar_bits_addr),
    .auto_out_ar_bits_len           (_axi4asink_auto_out_ar_bits_len),
    .auto_out_ar_bits_size          (_axi4asink_auto_out_ar_bits_size),
    .auto_out_ar_bits_burst         (_axi4asink_auto_out_ar_bits_burst),
    .auto_out_ar_bits_lock          (_axi4asink_auto_out_ar_bits_lock),
    .auto_out_ar_bits_prot          (_axi4asink_auto_out_ar_bits_prot),
    .auto_out_ar_bits_qos           (_axi4asink_auto_out_ar_bits_qos),
    .auto_out_r_ready               (_axi4asink_auto_out_r_ready)
  );

`ifdef XEPIC_P2E
        logic  [1:0]                      xram0_read;        
        logic  [127:0]                    xram0_read_addr;  
        logic  [1:0]                      xram0_read_data_ready; 
        logic  [1:0]                      xram0_write;       
        logic  [127:0]                    xram0_write_addr; 
        logic  [1151:0]                   xram0_write_data;    
        logic  [127:0]                    xram0_write_data_mask;
        
        logic  [1151:0]                   xram0_read_data;    
        logic  [1:0]                      xram0_read_data_valid;
        logic                             mmp_ddr4_calib_done;

         // slave0 slave-embeded, support burst control
         defparam u_axi_xram.AXI_MODE = 4;  // AXI Mode: 3 = AXI3, 4 = AXI4
         defparam u_axi_xram.AXI_ID_WIDTH   = 4;
         defparam u_axi_xram.AXI_DATA_WIDTH = 64;   // Data Width: 8,16,32,64,128,256,512,1024 
         defparam u_axi_xram.AXI_ADDR_WIDTH = 32;  // Addr Width: 32..64
         defparam u_axi_xram.AXI_USER_WIDTH = 0;  // 
         defparam u_axi_xram.MEM_SIZE = 64'h4_0000_0000;  // 2^34
 
         xaxi4_slave_emb u_axi_xram ( //or xaxi4_slave_emb_wrapper
            /*AUTOARG*/
            .aclk      (io_port_c0_sys_clk_i),
            .aresetn   (~io_port_sys_rst),
            // AXI write address channel
            .i_awvalid (_axi4asink_auto_out_aw_valid),
            .o_awready (_blackbox_c0_ddr4_s_axi_awready),
            .i_awid    (_axi4asink_auto_out_aw_bits_id),
            .i_awaddr  (_axi4asink_auto_out_aw_bits_addr[30:0]),
            .i_awlen   (_axi4asink_auto_out_aw_bits_len),     // in AXI3 .mode    (mode    ), [7:4] should be fixed to 0
            .i_awsize  (_axi4asink_auto_out_aw_bits_size),
            .i_awburst (_axi4asink_auto_out_aw_bits_burst),
            .i_awlock  (_axi4asink_auto_out_aw_bits_lock),
            .i_awcache (4'h3),
            .i_awprot  (_axi4asink_auto_out_aw_bits_prot),
            .i_awqos   (_axi4asink_auto_out_aw_bits_qos),
            .i_awregion(4'b0),
            // AXI write data channel
            .i_wvalid  (_axi4asink_auto_out_w_valid),
            .o_wready  (_blackbox_c0_ddr4_s_axi_wready),
            .i_wid     (0),
            .i_wdata   (_axi4asink_auto_out_w_bits_data),
            .i_wstrb   (_axi4asink_auto_out_w_bits_strb),
            .i_wlast   (_axi4asink_auto_out_w_bits_last),
            // AXI write response channel
            .o_bvalid  (_blackbox_c0_ddr4_s_axi_bvalid),
            .i_bready  (_axi4asink_auto_out_b_ready),
            .o_bid     (_blackbox_c0_ddr4_s_axi_bid),
            .o_bresp   (_blackbox_c0_ddr4_s_axi_bresp),

            // AXI read address channel
            .i_arvalid (_axi4asink_auto_out_ar_valid),
            .o_arready (_blackbox_c0_ddr4_s_axi_arready),
            .i_arid    (_axi4asink_auto_out_ar_bits_id),
            .i_araddr  (_axi4asink_auto_out_ar_bits_addr[30:0]),
            .i_arlen   (_axi4asink_auto_out_ar_bits_len),     // in AXI3 .mode    (mode    ), [7:4] should be fixed to 0
            .i_arsize  (_axi4asink_auto_out_ar_bits_size),
            .i_arburst (_axi4asink_auto_out_ar_bits_burst),
            .i_arlock  (_axi4asink_auto_out_ar_bits_lock),
            .i_arcache (4'h3),
            .i_arprot  (_axi4asink_auto_out_ar_bits_prot),
            .i_arqos   (_axi4asink_auto_out_ar_bits_qos),
            .i_arregion(4'b0),
            // AXI read response
            .o_rvalid  (_blackbox_c0_ddr4_s_axi_rvalid),
            .i_rready  (_axi4asink_auto_out_r_ready),
            .o_rid     (_blackbox_c0_ddr4_s_axi_rid),
            .o_rresp   (_blackbox_c0_ddr4_s_axi_rresp),
            .o_rdata   (_blackbox_c0_ddr4_s_axi_rdata),
            .o_rlast   (_blackbox_c0_ddr4_s_axi_rlast)
            );
    
        `ifdef XEPIC_XRAM_RTL
          xram_bbox_wrapper u_xram_bbox_wrapper (
              .uclk(io_port_c0_sys_clk_i),
              .xram0_read(xram0_read),
              .xram0_read_addr(xram0_read_addr),
              .xram0_read_data_ready(xram0_read_data_ready),
              .xram0_write(xram0_write),
              .xram0_write_addr(xram0_write_addr),
              .xram0_write_data(xram0_write_data),
              .xram0_write_data_mask(xram0_write_data_mask),
              .xram0_read_data(xram0_read_data),
              .xram0_read_data_valid(xram0_read_data_valid), 
              .mmp_ddr4_calib_done(_blackbox_c0_init_calib_complete)
          )/* synthesis syn_preserve=1 */;

          assign xram0_write[0]                  = u_axi_xram.write_xram;
          assign xram0_write_addr[0 +: 64]       = u_axi_xram.wr_addr_xram ;
          assign xram0_write_data[0 +: 576]      = u_axi_xram.wrdata_xram;
          assign xram0_write_data_mask[0 +: 64]  = u_axi_xram.wrdata_mask_xram;

          assign xram0_read[0]                   = 1'h0;
          assign xram0_read_addr[0 +: 64]        = 64'h0;
          assign xram0_read_data_ready[0]        = 1'h0;


          assign u_axi_xram.init_calib_complete = _blackbox_c0_init_calib_complete;

          assign xram0_write[1]                  = 1'h0;
          assign xram0_write_addr[64 +: 64]      = 64'h0;
          assign xram0_write_data[576 +: 576]    = 576'h0;
          assign xram0_write_data_mask[64 +: 64] = 64'h0;

          assign xram0_read[1]                   = u_axi_xram.read_xram;        
          assign xram0_read_addr[64 +: 64]       = u_axi_xram.rd_addr_xram;     
          assign xram0_read_data_ready[1]        = u_axi_xram.rddata_ready_xram;
          assign u_axi_xram.rddata_xram        = xram0_read_data[576 +: 576];
          assign u_axi_xram.rddata_valid_xram  = xram0_read_data_valid[1];
        `endif
        assign io_port_c0_ddr4_ui_clk = io_port_c0_sys_clk_i;
        assign io_port_c0_ddr4_ui_clk_sync_rst = 1'b0;

`else
  vcu118mig blackbox (	// @[XilinxVCU118MIG.scala:51:26]
    .c0_ddr4_dq              (io_port_c0_ddr4_dq),
    .c0_ddr4_dqs_c           (io_port_c0_ddr4_dqs_c),
    .c0_ddr4_dqs_t           (io_port_c0_ddr4_dqs_t),
    .c0_ddr4_dm_dbi_n        (io_port_c0_ddr4_dm_dbi_n),
    .c0_sys_clk_i            (io_port_c0_sys_clk_i),
    .c0_ddr4_aresetn         (io_port_c0_ddr4_aresetn),
    .sys_rst                 (io_port_sys_rst),
    .c0_ddr4_s_axi_awid      (_axi4asink_auto_out_aw_bits_id),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_awaddr    (_axi4asink_auto_out_aw_bits_addr[30:0]),	// @[AsyncCrossing.scala:72:31, XilinxVCU118MIG.scala:82:41]
    .c0_ddr4_s_axi_awlen     (_axi4asink_auto_out_aw_bits_len),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_awsize    (_axi4asink_auto_out_aw_bits_size),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_awburst   (_axi4asink_auto_out_aw_bits_burst),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_awlock    (_axi4asink_auto_out_aw_bits_lock),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_awcache   (4'h3),	// @[XilinxVCU118MIG.scala:92:39]
    .c0_ddr4_s_axi_awprot    (_axi4asink_auto_out_aw_bits_prot),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_awqos     (_axi4asink_auto_out_aw_bits_qos),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_awvalid   (_axi4asink_auto_out_aw_valid),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_wdata     (_axi4asink_auto_out_w_bits_data),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_wstrb     (_axi4asink_auto_out_w_bits_strb),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_wlast     (_axi4asink_auto_out_w_bits_last),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_wvalid    (_axi4asink_auto_out_w_valid),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_bready    (_axi4asink_auto_out_b_ready),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_arid      (_axi4asink_auto_out_ar_bits_id),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_araddr    (_axi4asink_auto_out_ar_bits_addr[30:0]),	// @[AsyncCrossing.scala:72:31, XilinxVCU118MIG.scala:83:41]
    .c0_ddr4_s_axi_arlen     (_axi4asink_auto_out_ar_bits_len),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_arsize    (_axi4asink_auto_out_ar_bits_size),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_arburst   (_axi4asink_auto_out_ar_bits_burst),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_arlock    (_axi4asink_auto_out_ar_bits_lock),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_arcache   (4'h3),	// @[XilinxVCU118MIG.scala:92:39]
    .c0_ddr4_s_axi_arprot    (_axi4asink_auto_out_ar_bits_prot),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_arqos     (_axi4asink_auto_out_ar_bits_qos),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_arvalid   (_axi4asink_auto_out_ar_valid),	// @[AsyncCrossing.scala:72:31]
    .c0_ddr4_s_axi_rready    (_axi4asink_auto_out_r_ready),	// @[AsyncCrossing.scala:72:31]    
    .c0_ddr4_adr             (io_port_c0_ddr4_adr),
    .c0_ddr4_bg              (io_port_c0_ddr4_bg),
    .c0_ddr4_ba              (io_port_c0_ddr4_ba),
    .c0_ddr4_reset_n         (io_port_c0_ddr4_reset_n),
    .c0_ddr4_act_n           (io_port_c0_ddr4_act_n),
    .c0_ddr4_ck_c            (io_port_c0_ddr4_ck_c),
    .c0_ddr4_ck_t            (io_port_c0_ddr4_ck_t),
    .c0_ddr4_cke             (io_port_c0_ddr4_cke),
    .c0_ddr4_cs_n            (io_port_c0_ddr4_cs_n),
    .c0_ddr4_odt             (io_port_c0_ddr4_odt),
    .c0_ddr4_ui_clk          (io_port_c0_ddr4_ui_clk),
    .c0_ddr4_ui_clk_sync_rst (io_port_c0_ddr4_ui_clk_sync_rst),
    .c0_init_calib_complete  (_blackbox_c0_init_calib_complete),
    .c0_ddr4_s_axi_awready   (_blackbox_c0_ddr4_s_axi_awready),
    .c0_ddr4_s_axi_wready    (_blackbox_c0_ddr4_s_axi_wready),
    .c0_ddr4_s_axi_bid       (_blackbox_c0_ddr4_s_axi_bid),
    .c0_ddr4_s_axi_bresp     (_blackbox_c0_ddr4_s_axi_bresp),
    .c0_ddr4_s_axi_bvalid    (_blackbox_c0_ddr4_s_axi_bvalid),
    .c0_ddr4_s_axi_arready   (_blackbox_c0_ddr4_s_axi_arready),
    .c0_ddr4_s_axi_rid       (_blackbox_c0_ddr4_s_axi_rid),
    .c0_ddr4_s_axi_rdata     (_blackbox_c0_ddr4_s_axi_rdata),
    .c0_ddr4_s_axi_rresp     (_blackbox_c0_ddr4_s_axi_rresp),
    .c0_ddr4_s_axi_rlast     (_blackbox_c0_ddr4_s_axi_rlast),
    .c0_ddr4_s_axi_rvalid    (_blackbox_c0_ddr4_s_axi_rvalid)
  );
`endif

endmodule

